In [ ]:
import tensorflow as tf

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split


In [ ]:
dt=pd.read_csv("/content/csv_result-bone-marrow.csv")

In [ ]:
dt.head()

id  Recipientgender  Stemcellsource   Donorage  Donorage35  IIIV  \
0   1                1               1  22.830137           0     1   
1   2                1               0  23.342466           0     1   
2   3                1               0  26.394521           0     1   
3   4                0               0  39.684932           1     1   
4   5                0               1  33.358904           0     0   

   Gendermatch  DonorABO RecipientABO RecipientRh  ... extcGvHD CD34kgx10d6  \
0            0         1            1           1  ...        1        7.20   
1            0        -1           -1           1  ...        1        4.50   
2            0        -1           -1           1  ...        1        7.94   
3            0         1            2           1  ...        ?        4.25   
4            0         1            2           0  ...        1       51.85   

    CD3dCD34 CD3dkgx10d8 Rbodymass  ANCrecovery  PLTrecovery  \
0    1.33876        5.38        35           19           51   
1  11.078295        0.41      20.6           16           37   
2   19.01323        0.42      23.4           23           20   
3  29.481647        0.14        50           23           29   
4   3.972255       13.05         9           14           14   

   time_to_aGvHD_III_IV  survival_time  survival_status  
0                    32            999                0  
1               1000000            163                1  
2               1000000            435                1  
3                    19             53                1  
4               1000000           2043                0  

[5 rows x 38 columns]

In [ ]:
dt.shape

(187, 38)

In [ ]:
dt.dtypes

id                        int64
Recipientgender           int64
Stemcellsource            int64
Donorage                float64
Donorage35                int64
IIIV                      int64
Gendermatch               int64
DonorABO                  int64
RecipientABO             object
RecipientRh              object
ABOmatch                 object
CMVstatus                object
DonorCMV                 object
RecipientCMV             object
Disease                  object
Riskgroup                 int64
Txpostrelapse             int64
Diseasegroup              int64
HLAmatch                  int64
HLAmismatch               int64
Antigen                  object
Alel                     object
HLAgrI                    int64
Recipientage            float64
Recipientage10            int64
Recipientageint           int64
Relapse                   int64
aGvHDIIIIV                int64
extcGvHD                 object
CD34kgx10d6             float64
CD3dCD34                 object
CD3dkgx1

In [ ]:
dt.dropna()

id  Recipientgender  Stemcellsource   Donorage  Donorage35  IIIV  \
0      1                1               1  22.830137           0     1   
1      2                1               0  23.342466           0     1   
2      3                1               0  26.394521           0     1   
3      4                0               0  39.684932           1     1   
4      5                0               1  33.358904           0     0   
..   ...              ...             ...        ...         ...   ...   
182  183                1               1  37.575342           1     1   
183  184                0               1  22.895890           0     0   
184  185                0               1  27.347945           0     1   
185  186                1               1  27.780822           0     1   
186  187                1               1  55.553425           1     1   

     Gendermatch  DonorABO RecipientABO RecipientRh  ... extcGvHD CD34kgx10d6  \
0              0         1            1           1  ...        1        7.20   
1              0        -1           -1           1  ...        1        4.50   
2              0        -1           -1           1  ...        1        7.94   
3              0         1            2           1  ...        ?        4.25   
4              0         1            2           0  ...        1       51.85   
..           ...       ...          ...         ...  ...      ...         ...   
182            0         1            1           0  ...        1       11.08   
183            0         1            0           1  ...        1        4.64   
184            0         1           -1           1  ...        1        7.73   
185            0         1            0           1  ...        0       15.41   
186            0         1            2           1  ...        1        9.91   

      CD3dCD34 CD3dkgx10d8 Rbodymass  ANCrecovery  PLTrecovery  \
0      1.33876        5.38        35           19           51   
1    11.078295        0.41      20.6           16           37   
2     19.01323        0.42      23.4           23           20   
3    29.481647        0.14        50           23           29   
4     3.972255       13.05         9           14           14   
..         ...         ...       ...          ...          ...   
182    2.52275        4.39        44           15           22   
183   1.038858        4.47      44.5           12           30   
184   1.635559        4.73        33           16           16   
185    8.07777        1.91        24           13           14   
186   0.948135       10.45        37           18           20   

     time_to_aGvHD_III_IV  survival_time  survival_status  
0                      32            999                0  
1                 1000000            163                1  
2                 1000000            435                1  
3                      19             53                1  
4                 1000000           2043                0  
..                    ...            ...              ...  
182                    16            385                1  
183               1000000            634                1  
184               1000000           1895                0  
185                    54            382                1  
186               1000000           1109                0  

[187 rows x 38 columns]

In [ ]:
cor=abs(dt.corr(method="pearson"))
relevant_features = cor[cor<0.5]
list4=relevant_features.keys().to_list()
list4

['id',
 'Recipientgender',
 'Stemcellsource',
 'Donorage',
 'Donorage35',
 'IIIV',
 'Gendermatch',
 'DonorABO',
 'Riskgroup',
 'Txpostrelapse',
 'Diseasegroup',
 'HLAmatch',
 'HLAmismatch',
 'HLAgrI',
 'Recipientage',
 'Recipientage10',
 'Recipientageint',
 'Relapse',
 'aGvHDIIIIV',
 'CD34kgx10d6',
 'ANCrecovery',
 'PLTrecovery',
 'time_to_aGvHD_III_IV',
 'survival_time',
 'survival_status']

In [ ]:
coloums=['Recipientgender','Stemcellsource','Donorage','Donorage35','IIIV','Gendermatch','DonorABO','Riskgroup','Txpostrelapse','Diseasegroup','HLAmatch','HLAmismatch','HLAgrI','Recipientage','Recipientage10','Recipientageint','Relapse','aGvHDIIIIV','CD34kgx10d6','ANCrecovery','PLTrecovery','time_to_aGvHD_III_IV','survival_time',]
x=dt[coloums]
y=dt["survival_status"]


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()
x=scaler.fit_transform(x)


In [ ]:
x

array([[ 0.81831709,  0.53819622, -1.28998124, ..., -0.31616067,
        -1.8580561 ,  0.07111487],
       [ 0.81831709, -1.85805838, -1.22787834, ..., -0.31620937,
         0.53819622, -0.91553139],
       [ 0.81831709, -1.85805838, -0.85791788, ..., -0.3162685 ,
         0.53819622, -0.5945173 ],
       ...,
       [-1.22202019,  0.53819622, -0.74234683, ..., -0.31628242,
         0.53819622,  1.12857307],
       [ 0.81831709,  0.53819622, -0.68987485, ..., -0.31628938,
        -1.85800338, -0.65706784],
       [ 0.81831709,  0.53819622,  2.67663232, ..., -0.3162685 ,
         0.53819622,  0.20093675]])

In [ ]:
df = pd.DataFrame(x)
df.to_csv("processed_data.csv")

In [ ]:
y.value_counts()

0    102
1     85
Name: survival_status, dtype: int64

In [ ]:
train_X, val_X, train_y, val_y = train_test_split(x, y, random_state=1,train_size=0.8)


In [ ]:
rnn = Sequential()

In [ ]:
rnn.add(LSTM(units = 45, return_sequences = True, input_shape = (train_X.shape[1], 1)))

In [ ]:
rnn.add(Dropout(0.2))

In [ ]:
rnn.add(LSTM(units = 45, return_sequences = True))

rnn.add(Dropout(0.2))

rnn.add(LSTM(units = 45, return_sequences = True))

rnn.add(Dropout(0.2))

rnn.add(LSTM(units = 45))

rnn.add(Dropout(0.2))

In [ ]:
rnn.add(Dense(units = 1))

In [ ]:
rnn.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
rnn.fit(train_X,train_y, epochs = 100, batch_size = 32)

Epoch 1/100
5/5 [==============================] - 8s 45ms/step - loss: 0.3993
Epoch 2/100
5/5 [==============================] - 0s 48ms/step - loss: 0.2600
Epoch 3/100
5/5 [==============================] - 0s 47ms/step - loss: 0.2652
Epoch 4/100
5/5 [==============================] - 0s 53ms/step - loss: 0.2363
Epoch 5/100
5/5 [==============================] - 0s 52ms/step - loss: 0.2396
Epoch 6/100
5/5 [==============================] - 0s 44ms/step - loss: 0.2270
Epoch 7/100
5/5 [==============================] - 0s 44ms/step - loss: 0.2336
Epoch 8/100
5/5 [==============================] - 0s 66ms/step - loss: 0.2326
Epoch 9/100
5/5 [==============================] - 0s 74ms/step - loss: 0.2282
Epoch 10/100
5/5 [==============================] - 0s 79ms/step - loss: 0.2338
Epoch 11/100
5/5 [==============================] - 0s 95ms/step - loss: 0.2264
Epoch 12/100
5/5 [==============================] - 0s 94ms/step - loss: 0.2269
Epoch 13/100
5/5 [==============================]

In [ ]:
predictions = rnn.predict(val_X)

2/2 [==============================] - 2s 16ms/step


In [ ]:
from sklearn.metrics import mean_squared_error as MSE

In [ ]:
mse_rnn = MSE(val_y,predictions)

In [ ]:
mse_rnn

0.2751382864080406

In [ ]:
import sklearn.metrics as metrics
from sklearn.metrics import classification_report

In [ ]:
print('\nRNN')
print('Accuracy Score:',metrics.accuracy_score(val_y,predictions.round())*100,'%',sep='')
print('Confusion Matrix:',metrics.confusion_matrix(val_y,predictions.round()),sep='\n')
print(classification_report(val_y,predictions.round()))


RNN
Accuracy Score:60.526315789473685%
Confusion Matrix:
[[ 9 12]
 [ 3 14]]
              precision    recall  f1-score   support

           0       0.75      0.43      0.55        21
           1       0.54      0.82      0.65        17

    accuracy                           0.61        38
   macro avg       0.64      0.63      0.60        38
weighted avg       0.66      0.61      0.59        38



In [ ]:
pip install pyGRNN --ignore-installed

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 86.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 KB 35.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 89.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 17.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 75.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 90.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 35.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.7/299.7 KB 37.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 74.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 80.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━

In [ ]:
from pyGRNN import GRNN

In [ ]:
AGRNN = GRNN(calibration = 'gradient_search')

In [ ]:
AGRNN.fit(train_X,train_y.ravel())

GRNN(bnds=((0, None), (0, None), (0, None), (0, None), (0, None), (0, None),
           (0, None), (0, None), (0, None), (0, None), (0, None), (0, None),
           (0, None), (0, None), (0, None), (0, None), (0, None), (0, None),
           (0, None), (0, None), (0, None), (0, None), (0, None)),
     calibration='gradient_search',
     sigma=array([1.83603362, 3.08831085, 1.08513261, 1.03598389, 1.20422371,
       1.84695947, 5.04540702, 2.65294255, 1.39780384, 1.42933333,
       0.09986098, 0.40229152, 0.5511398 , 0.05917812, 3.28310522,
       1.32209515, 0.12347643, 0.20687221, 0.09044698, 0.39999629,
       0.40014217, 0.20194209, 0.01497752]))

In [ ]:
sigma = AGRNN.sigma

In [ ]:
prediction = AGRNN.predict(val_X)

In [ ]:
mse_AGRNN = MSE(val_y,predictions)
mse_AGRNN

0.2520404436640936

In [ ]:
print('\nGRNN')
print('Accuracy Score:',metrics.accuracy_score(val_y,prediction.round())*100,'%',sep='')
print('Confusion Matrix:',metrics.confusion_matrix(val_y,prediction.round()),sep='\n')
print(classification_report(val_y,prediction.round()))


GRNN
Accuracy Score:86.8421052631579%
Confusion Matrix:
[[17  4]
 [ 1 16]]
              precision    recall  f1-score   support

           0       0.94      0.81      0.87        21
           1       0.80      0.94      0.86        17

    accuracy                           0.87        38
   macro avg       0.87      0.88      0.87        38
weighted avg       0.88      0.87      0.87        38



In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
ann.fit(train_X,train_y,batch_size=32,epochs = 75)

Epoch 1/75
5/5 [==============================] - 1s 4ms/step - loss: 0.7110 - accuracy: 0.4631
Epoch 2/75
5/5 [==============================] - 0s 6ms/step - loss: 0.7025 - accuracy: 0.4832
Epoch 3/75
5/5 [==============================] - 0s 4ms/step - loss: 0.6943 - accuracy: 0.4966
Epoch 4/75
5/5 [==============================] - 0s 4ms/step - loss: 0.6883 - accuracy: 0.4966
Epoch 5/75
5/5 [==============================] - 0s 4ms/step - loss: 0.6813 - accuracy: 0.5168
Epoch 6/75
5/5 [==============================] - 0s 4ms/step - loss: 0.6754 - accuracy: 0.5168
Epoch 7/75
5/5 [==============================] - 0s 5ms/step - loss: 0.6698 - accuracy: 0.5302
Epoch 8/75
5/5 [==============================] - 0s 5ms/step - loss: 0.6639 - accuracy: 0.5503
Epoch 9/75
5/5 [==============================] - 0s 4ms/step - loss: 0.6589 - accuracy: 0.5638
Epoch 10/75
5/5 [==============================] - 0s 5ms/step - loss: 0.6539 - accuracy: 0.5570
Epoch 11/75
5/5 [======================

In [ ]:
predict = ann.predict(val_X)

2/2 [==============================] - 0s 5ms/step


In [ ]:
mse_ann = MSE(val_y,predict)
mse_ann

0.15427872263024417

In [ ]:
print('\nANN')
print('Accuracy Score:',metrics.accuracy_score(val_y,predict.round())*100,'%',sep='')
print('Confusion Matrix:',metrics.confusion_matrix(val_y,predict.round()),sep='\n')
print(classification_report(val_y,predict.round()))


ANN
Accuracy Score:78.94736842105263%
Confusion Matrix:
[[18  3]
 [ 5 12]]
              precision    recall  f1-score   support

           0       0.78      0.86      0.82        21
           1       0.80      0.71      0.75        17

    accuracy                           0.79        38
   macro avg       0.79      0.78      0.78        38
weighted avg       0.79      0.79      0.79        38

